services:
  - type: web
    name: real-estate-backend
    env: node
    buildCommand: cp package-deploy.json package.json && npm install
    startCommand: node backend/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d 